####################################
# PUTTANTOUR
####################################
puttantour.online {
	encode gzip zstd
	reverse_proxy 127.0.0.1:8999
}

www.puttantour.online {
	redir https://puttantour.online{uri} permanent
}
